### ISSUE TITLE
It is possible to change the border solid heigh?

### ISSUE THREAD

**Issue by CristianEstiber** [tiagobalmeida/purecss-circular-progress-bar#1]
I mean, imagine when you have a rectangle like that 

`p.one {
  border-style: solid;
  border-width: 5px;
}`

and if you want the border smaller you will do border-width: 1px; for example, its possible to do the same with the circle background and circle progress bar?

**Comment by tiagobalmeida** [comment]
It is but not that simply.

 The "border" in this implementation is made by overlaying a circle with a smaller circle on top. If one has a radius of 10, the other of 8, there's a difference of 2 for "border". 

Read here how it is built: 
https://jumpifzero.github.io/posts/making-a-pure-css-circular-progress-bar.html
